version: '3.8'
services:
  account-manager-api: 
    container_name: account-manager-api
    build:
      context: ./
      target: development
      dockerfile: Dockerfile
    command: npm run start:dev
    restart: always
    volumes:
      - .:/usr/src/app
    env_file: 
      - .env/local.env
    ports:
      - "3000:3000"
    networks: 
      - broker-project
    depends_on: 
      - account-manager-database
      
  account-manager-database:
    image: postgres
    container_name: 'account-manager-database'
    volumes:
      - ./postgresql:/var/lib/postgresql/data_account_manager
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - broker-project

volumes:
  database_account-manager:

networks:
  broker-project:
    external: true